import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en " className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#F2F2F2] min-h-full flex flex-col justify-between`}
      >
        <header className="flex justify-between pt-6 px-[65px]">
          <h1 className="font-bold text-xl text-[#282796]">DOCAID</h1>
          <button className="bg-[#282796] text-white px-8 py-4 font-bold rounded-lg">
            Logout
          </button>
        </header>
        {children}
        <footer className="bg-[#282796] h-[178px] flex flex-col justify-end p-7">
          <p className="text-white text-xl">All rights reserved by MedAura</p>
        </footer>
      </body>
    </html>
  );
}
